### ISSUE TITLE
[Question] Unable to run the sample?

### ISSUE THREAD

**Issue by aloksharma1** [EasyAbp/Abp.DynamicEntity#10]
hello, 
i have been going through your sample and getting error run command is not defined when i try to run the web sample.
 
Also it looks like this lib only doing simple crud, but what if we have related complex entities does this library handles that?

**Comment by gdlcf88** [comment]
The sample project has been fixed by https://github.com/EasyAbp/Abp.DynamicEntity/commit/17cbf232d2805a5722fd38e7990358ceaca836fb. Please pull the master branch.

**Comment by aloksharma1** [comment]
still not working for me, now the error is due to unable to find the sample database from this conn string `"Server=(LocalDb)\\MSSQLLocalDB;Database=DynamicEntitySample;Trusted_Connection=True"` can you check and put this file in git.

**Comment by gdlcf88** [comment]
You don't need any extra files. Please go to the ABP docs site to learn how to run module sample projects.
